### ISSUE TITLE
Windows 10 ISO file !

### ISSUE THREAD

**Issue by jacobapps** [amodm/iso9660-swift#1]
Hi dear developer,

I cannot read and get list files from windows 10 iso file, I thinking it's about ISO file size, for example I test small file and working well.
when I use:
let directoryEntry = try! fileSystem.getFSEntry("/")
after that code not working.
also I cannot get error message.

Thanks a lot.

**Comment by amodm** [comment]
If you're trying to use this lib to open a windows install ISO, that's very likely happening because they're in the UDF format, which has some basic compatibility with ISO9660, but requires a UDF aware library. This library is strictly a ISO9660 lib, and isn't UDF aware.

I don't have any timelines for baking that support yet, but a PR is gladly welcome.

**Comment by jacobapps** [comment]
Thanks for your help
